version: '3'

services:
  nginx:
    image: nginx
    container_name: inethi-nginx-splash
    restart: always
    volumes:
        - "${NGINX_VOLUME}/html:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.splash.rule=Host(`${TRAEFIK_API_RULE_HOST}.${inethiDN}`)"
      - "traefik.http.routers.splash.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
